Loading vasp version 6.3.0

Some pseudo-potentials are available at:
 /apps/exported/installed/software/vasp/PP/

To use one of the nonlocal vdW functionals one needs to put the file vdw_kernel.bindat into the run directory. This file can be found at:
 /apps/exported/installed/software/vasp/vdw_kernel/

TO BE AWARE: There is a known bug regarding the INCAR file, if the code is complaining due to an error in a FLAG of your INCAR file, please open it with the vi editor and type ':set ff=unix'.


Loading vasp/6.3.0
  Loading requirement: intel/oneAPI/2023.0.0 intel/szip/2.1.1 intel/zlib/1.2.13
    intel/hdf5/1.14.0 intel/dftd4/3.4.0

Loading Conda/Python version 4.14.0/3.9
Traceback (most recent call last):
  File "/home/mgonzalez/pyFDBM/prepare_calculation.py", line 169, in <module>
    sample  = read(sample_path) if do_samp else None
  File "/home/mgonzalez/.conda/envs/pyFDBMenv/lib/python3.9/site-packages/ase/utils/__init__.py", line 483, in iofunc
    fd = open(str(file), self.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'sample/CHGCAR'
Traceback (most recent call last):
  File "/home/mgonzalez/pyFDBM/density_interactions.py", line 28, in <module>
    sample_data = np.load(p.SAMPLE/'sample.npz')
  File "/home/mgonzalez/.conda/envs/pyFDBMenv/lib/python3.9/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'sample/sample.npz'
Traceback (most recent call last):
  File "/home/mgonzalez/pyFDBM/dftd3-py.py", line 60, in <module>
    tip     = read(str(p.TIP/'CHGCAR'))
  File "/home/mgonzalez/.conda/envs/pyFDBMenv/lib/python3.9/site-packages/ase/utils/__init__.py", line 483, in iofunc
    fd = open(str(file), self.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'tip/CHGCAR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mgonzalez/pyFDBM/dftd3-py.py", line 62, in <module>
    tip     = read(str(p.TIP/'CONTCAR'))
  File "/home/mgonzalez/.conda/envs/pyFDBMenv/lib/python3.9/site-packages/ase/utils/__init__.py", line 483, in iofunc
    fd = open(str(file), self.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'tip/CONTCAR'
srun: Job step aborted: Waiting up to 62 seconds for job step to finish.
slurmstepd: error: *** STEP 7474.0 ON node-02 CANCELLED AT 2023-12-14T15:25:35 ***
slurmstepd: error: *** JOB 7474 ON node-02 CANCELLED AT 2023-12-14T15:25:35 ***
